name: Updater
on:
  schedule:
    - cron: '37 13 * * *'
  workflow_dispatch:
jobs:
  Update-Apks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: 'product/app/updater/Pipfile.lock'
      - run: pipenv install
        working-directory: 'product/app/updater'
      - run: pipenv run python main.py
        working-directory: 'product/app/updater'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: 'product/priv-app/updater/Pipfile.lock'
      - run: pipenv install
        working-directory: 'product/priv-app/updater'
      - run: pipenv run python main.py
        working-directory: 'product/priv-app/updater'
